// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DENTAL_WPF.Models;

public partial class DentalClinic
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Country { get; set; }

    public string City { get; set; }

    public int? LicenseId { get; set; }

    public virtual ICollection<Dentist> Dentists { get; set; } = new List<Dentist>();

    public virtual License License { get; set; }
}