// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DENTAL_WPF.Models;

public partial class License
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string IssuingCompany { get; set; }

    public virtual ICollection<DentalClinic> DentalClinics { get; set; } = new List<DentalClinic>();
}